export const TOKENS = {
  // ===== REPOSITORIES =====
  DOCUMENT_REPOSITORY: Symbol.for('DOCUMENT_REPOSITORY'),
  DOCUMENT_VERSION_REPOSITORY: Symbol.for('DOCUMENT_VERSION_REPOSITORY'),
  ACCESS_POLICY_REPOSITORY: Symbol.for('ACCESS_POLICY_REPOSITORY'),
  DOWNLOAD_TOKEN_REPOSITORY: Symbol.for('DOWNLOAD_TOKEN_REPOSITORY'),
  USER_REPOSITORY: Symbol.for('USER_REPOSITORY'),

  // ===== PORTS =====
  FILE_STORAGE_PORT: Symbol.for('FILE_STORAGE_PORT'),
  PASSWORD_HASHER_PORT: Symbol.for('PASSWORD_HASHER_PORT'),
  AUTH_TOKEN_PORT: Symbol.for('AUTH_TOKEN_PORT'),
  CONFIG_PORT: Symbol.for('CONFIG_PORT'),
  LOGGER_PORT: Symbol.for('LOGGER_PORT'),
  AUDIT_PORT: Symbol.for('AUDIT_PORT'),

  // ===== WORKFLOWS =====
  DOCUMENT_WORKFLOW: Symbol.for('DOCUMENT_WORKFLOW'),
  DOCUMENT_VERSION_WORKFLOW: Symbol.for('DOCUMENT_VERSION_WORKFLOW'),
  UPLOAD_WORKFLOW: Symbol.for('UPLOAD_WORKFLOW'),
  ACCESS_POLICY_WORKFLOW: Symbol.for('ACCESS_POLICY_WORKFLOW'),
  DOWNLOAD_TOKEN_WORKFLOW: Symbol.for('DOWNLOAD_TOKEN_WORKFLOW'),
  USER_WORKFLOW: Symbol.for('USER_WORKFLOW'),

  // ===== DATABASE =====
  DATABASE_CONNECTION: Symbol.for('DATABASE_CONNECTION'),
} as const

export type TokenKey = keyof typeof TOKENS
export type TokenValue = typeof TOKENS[TokenKey]
