import { env } from "@infra/config/env";
import type { ConfigPort } from "@/app/application/services/ports/config.port";

export function loadConfig(): ConfigPort {
  return {
    NODE_ENV: env.NODE_ENV,
    PORT: env.PORT,

    DATABASE_URL: env.DATABASE_URL,
    DATABASE_POOL_SIZE: env.DATABASE_POOL_SIZE,
    DATABASE_TIMEOUT: env.DATABASE_TIMEOUT,

    JWT_SECRET: env.JWT_SECRET,
    JWT_EXPIRES_IN: env.JWT_EXPIRES_IN,
    JWT_REFRESH_EXPIRES_IN: env.JWT_REFRESH_EXPIRES_IN,

    BCRYPT_SALT_ROUNDS: env.BCRYPT_SALT_ROUNDS,

    STORAGE_PATH: env.STORAGE_PATH,
    ALLOWED_MIME_TYPES: env.ALLOWED_MIME_TYPES,

    CORS_ORIGINS: env.CORS_ORIGINS,
    DOWNLOAD_TOKEN_CLOCK_SKEW_TOLERANCE_MS: env.DOWNLOAD_TOKEN_CLOCK_SKEW_TOLERANCE_MS,
    LOG_LEVEL: env.LOG_LEVEL,
    LOG_FORMAT: env.LOG_FORMAT,
    RATE_LIMIT_WINDOW_MS: env.RATE_LIMIT_WINDOW_MS,
    RATE_LIMIT_MAX_REQUESTS: env.RATE_LIMIT_MAX_REQUESTS,
    HEALTH_CHECK_TIMEOUT: env.HEALTH_CHECK_TIMEOUT,
  };
}

